---
collections:
  - name: community.general
    source: https://galaxy.ansible.com

  - name: ansible.utils
    source: https://galaxy.ansible.com
#
#  - name: ansible.posix.sysctl
#    source: https://galaxy.ansible.com
