---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
    version: "<15.0.0"

  - name: ansible.utils
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

  - name: kubernetes.core
    source: https://galaxy.ansible.com

  - name: freeipa.ansible_freeipa
    source: https://galaxy.ansible.com
