#!/usr/bin/env python

import requests
import sys
import json

print(json.dumps({"all": {"hosts": ["localhost"]}}))
#url = "https://cmdb.pieter.fish/api/cmdb/devices"
#headers = {}
#params = {}
#response = requests.get(url)
#data = response.json()
#
#print(data)


