#!/usr/bin/env python3

import requests
import json

url = "https://cmdb.pieter.fish/api/cmdb/devices/inventory"
headers = {}
params = {}
response = requests.get(url)
data = json.dumps(response.json())

print(str(data))


