# TEMPLATE:
#
# GROUPNAME:
#  hosts:
#    HOSTNAME:         DNS RECORDS ARE PUBLISHED TO THE PIETER.FISH ZONE AUTOMATICALLY, 
#                      MAKE SURE HOSTNAME IS A VALID FQDN
#
#      vlan: X         NOT SET BY DEFAULT, REQUIRED, RANGE OF 0-255
#      id: X           NOT SET BY DEFAULT, REQUIRED, RANGE OF 2-254
#      cpu: 4          DEFAULT VALUE, OPTIONAL
#      memory: 4096    DEFAULT VALUE, OPTIONAL
#      disk: 20        DEFAULT VALUE, OPTIONAL
#      os: debian      DEFAULT VALUE, OPTIONAL; TO CHANGE OS DEFINE AS: 'Alma-Linux'
#      state: 'started'  DEFAULT VALUE, OPTIONAL, OPTIONS: 'started' OR 'stopped'
#      deploy: true    DEFAULT VALUE, OPTIONAL, OPTIONS: true OR false setting this to valse disables all previously listed options
#      ansible_managed: true DEFAULT VALUE, OPTIONAL, OPTIONS: true OR false. IF FALSE, AWX WONT EXECUTE PLAYBOOKS ON THIS HOST
#
#      
#
# IF YOU WANT TO KEEP A VM WHICH IS NOT MANAGED BY THE AUTOMATIC DEPLOY ADD ITS ID TO THE VARS:
# roles/vm-cleanup/vars/main.yml

####################
ungrouped:         #
  hosts:           #
####################

#    OPNsense:
#      cpu: 8
#      memory: 4096
#      disk: 32
#      deploy: false

    wireguard.pieter.fish:
      vlan: 99
      id: 10
      zabbix: enabled

    rex.awx.pieter.fish:
      vlan: 50
      id: 13
      os: Alma-Linux
      ansible_managed: false

    idm.nauvis.lan:
      vlan: 50
      id: 14
      os: Alma-Linux
      ansible_host: 10.1.50.14
      ipa.domain: nauvis.lan
      ipa.realm: NAUVIS.LAN
      ipa.admin.password: test
      ipa.dm.password: test

    hop.awx.pieter.fish:
      vlan: 103
      id: 7
      os: Alma-Linux
      ansible_managed: false

    netbox-psql.pieter.fish:
      vlan: 103
      id: 8

    puppet.pieter.fish:
      vlan: 105
      id: 10
      os: Alma-Linux
      memory: 8192
      cpu: 4

    puppet-client.pieter.fish:
      vlan: 105
      id: 20
      os: Alma-Linux

    rundeck.pieter.fish:
      vlan: 50
      id: 17

####################
zabbix:            #
  hosts:           #
####################

    zbx-proxy-htz01.pieter.fish:
      vlan: 50
      id: 11
      disk: 30

    zbx-server-htz01.pieter.fish:
      vlan: 50
      id: 12
      disk: 100
      memory: 8192

####################
webservers:        #
  hosts:           #
####################

    immich.pieter.fish:
      vlan: 100
      id: 11
      disk: 150
      memory: 8192
      zabbix: enabled

    bookstack.web.pieter.fish:
      vlan: 100
      id: 12 
      disk: 50
      zabbix: enabled

    web01.pieter.fish:
      vlan: 100
      id: 17 
      zabbix: enabled

####################
proxies:           #
  hosts:           #
####################

    webproxy.pieter.fish:
      vlan: 100
      id: 16
      zabbix: enabled

    kube-ha-00.pieter.fish:
      vlan: 103
      id: 13 
      zabbix: enabled

    kube-ha-01.pieter.fish:
      vlan: 103
      id: 14
      zabbix: enabled

####################
kubernetes:        #
  hosts:           #
####################

    kube-master-00.pieter.fish:
      vlan: 103
      id: 10

    kube-master-01.pieter.fish:
      vlan: 103
      id: 11

    kube-master-02.pieter.fish:
      vlan: 103
      id: 12

    kube-worker-00.pieter.fish:
      vlan: 103
      id: 20
      disk: 50
      memory: 8192

    kube-worker-01.pieter.fish:
      vlan: 103
      id: 21
      disk: 50
      memory: 8192

    kube-worker-02.pieter.fish:
      vlan: 103
      id: 22
      disk: 50
      memory: 8192

#####################
#eva:               #
#  hosts:           #
#####################
#
#    eva--00.?.local:
#      vlan: 106
#      id: 10
#      kubernetes: enabled
#      role: master
#      bootstrap: true
#      release: v1.31
#      api_endpoint: api.eva.?.local

####################
docker:            #
  hosts:           #
####################

    docker-repo.pieter.fish:
      vlan: 103
      id: 05
      disk: 30
      zabbix: enabled

####################
nick:              #
  hosts:           #
####################

    NicksFuckUp.pieter.fish:
      vlan: 101
      id: 11
      custom_root_password: "{{ vaulted_nick_password }}"
      zabbix: enabled

    NicksWebServer.pieter.fish:
      vlan: 101
      id: 12
      custom_root_password: "{{ vaulted_nick_password }}"
      zabbix: enabled
      
    nick-mail.pieter.fish:
      vlan: 101
      id: 13
      custom_root_password: "{{ vaulted_nick_password }}"
      zabbix: enabled

    nick-mail-test.pieter.fish:
      vlan: 101
      id: 14
      custom_root_password: "{{ vaulted_nick_password }}"
      zabbix: enabled

####################
OKD:               #
  hosts:           #
####################

    bootstrap.okd.pieter.fish:
      vlan: 104
      id: 2
      disk: 120
      memory: 16384 
      state: stopped

    services.okd.pieter.fish:
      vlan: 104
      id: 3
      disk: 120
      memory: 16384
      state: stopped

    master00.okd.pieter.fish:
      vlan: 104
      id: 20
      disk: 120
      memory: 16384 
      state: stopped

    master01.okd.pieter.fish:
      vlan: 104
      id: 21
      disk: 120
      memory: 16384 
      state: stopped

    master02.okd.pieter.fish:
      vlan: 104
      id: 22
      disk: 120
      memory: 16384 
      state: stopped

    worker00.okd.pieter.fish:
      vlan: 104
      id: 30
      disk: 120
      memory: 16384 
      state: stopped

    worker01.okd.pieter.fish:
      vlan: 104
      id: 31
      disk: 120
      memory: 16384 
      state: stopped

    worker02.okd.pieter.fish:
      vlan: 104
      id: 32
      disk: 120
      memory: 16384 
      state: stopped
