- hosts: all 
  become: yes 
  gather_facts: no
  vars_files:
   - secrets/vault.yml
  tasks:
   # START VM DEPLOY ON LOCALHOST
    - name: include vm deploy role 
      include_role:
        name: vm-deploy 
        apply:
          delegate_to: localhost
      when: deploy | default(true) 
      tags: deploy

    # START VM DELETION ON LOCALHOST
    - name: include vm-cleanup role 
      include_role:
        name: vm-cleanup
        apply:
          delegate_to: localhost
      when: deploy | default(true)
      tags: deploy 

    - name: remove stopped machines from play 
      ansible.builtin.meta: end_host
      when: 
      - state is defined 
      - state == "stopped"
      tags: always

    - name: gather facts
      setup:
      tags: always

    # INSTALL ZABBIX AGENT
    - name: include zabbix role 
      import_role:
        name: zabbix 
      when: 
      - zabbix is defined 
      - zabbix == "enabled"
      tags: zabbix

    # INSTALL KUBERNETES CORE ON KUBERNETES NODES 
    - name: install kubernetes core
      include_role:
        name: kubernetes-core
      when: kubernetes is defined 
      tags: kubernetes
