- name: install dependencies
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - nfs-common

- name: install k8s key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ release }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
    state: present

- name: install k8s repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ release }}/deb/ /
    filename: kubernetes

- name: install kubernetes and componets
  ansible.builtin.apt:
    pkg:
    - kubeadm
    - kubectl
    - kubelet

- name: hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold

- name: hold kubectl
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: hold kubelet
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold
