  - name: gather public keys
    ansible.builtin.assemble:
      src: "templates/ssh/"
      dest: "/tmp/ssh_keys"
      mode: 0644
    become: false
    run_once: true

  - name: set vmid
    ansible.builtin.set_fact: 
      vmid: "{{ ip.split('.')[2:4] | join('') }}"

  - name: set vlan
    ansible.builtin.set_fact: 
      vlan: "{{ ip.split('.')[2] }}"

  - name: set subnet
    ansible.builtin.set_fact: 
      subnet: "{{ ip.split('.')[0:3] | join('.') }}"

  - name: debug ip info
    ansible.builtin.debug:
      msg: "ip={{ ip }}/{{ cidr }},gw={{ subnet }}.{{ gateway }}"

  - name: define os_id for Debian 
    ansible.builtin.set_fact:
      os_id: 9998
    when: os == "Debian"

  - name: define os_id for Alma Linux
    ansible.builtin.set_fact:
      os_id: 9999
    when: os == "Alma-Linux"

  - name: Create a full clone of template
    community.general.proxmox_kvm:
      node: "{{ node_name }}"
      api_user: "{{ user }}"
      api_password: "{{ ansible_password }}"
      api_host: "{{ node_name }}.{{ node_domain }}"
      clone: template
      vmid: "{{ os_id }}" 
      newid: "{{ vmid }}"
      name: "{{ hostname }}"
      storage: "{{ storage }}"
      format: "{{ format }}"
      timeout: 120

  - name: modify vm to specified specs 
    community.general.proxmox_kvm:
      node: "{{ node_name }}"
      api_user: "{{ user }}"
      api_password: "{{ ansible_password }}"
      api_host: "{{ node_name }}.{{ node_domain }}"
      vmid: "{{ vmid }}"
      cores: "{{ cpu | default(4) }}"
      memory: "{{ memory | default(4096) }}"
      ipconfig: 
        ipconfig0: "ip={{ ip }}/{{ cidr }},gw={{ subnet }}.{{ gateway }}"
      ciuser: "ansible"
      cipassword: "{{ ansible_password }}"
      sshkeys: "{{ lookup('ansible.builtin.file','/tmp/ssh_keys') }}"
      update: true 
    ignore_errors: yes

  - name: set vlan tag on net_0
    community.general.proxmox_nic:
      api_user: "{{ user }}"
      api_password: "{{ ansible_password }}"
      api_host: "{{ node_name }}.{{ node_domain }}"
      vmid: "{{ vmid }}"
      interface: net0
      bridge: "{{ bridge }}"
      tag: "{{ vlan }}"

  - name: Grow existing disk
    community.general.proxmox_disk:
      api_host: "{{ node_name }}.{{ node_domain }}"
      api_user: "{{ user }}"
      api_password: "{{ ansible_password }}"
      vmid: "{{ vmid }}" 
      disk: scsi0
      size: "{{ disk | default(20)}}G"
      state: resized

  - name: change state of the VM 
    community.general.proxmox_kvm:
      node: "{{ node_name }}"
      api_user: "{{ user }}"
      api_password: "{{ ansible_password }}"
      api_host: "{{ node_name }}.{{ node_domain }}"
      vmid: "{{ vmid }}"
      state: "{{ state | default('started') }}"
    register: newState

  - name: wait if power state has changed
    ansible.builtin.wait_for:
      timeout: 60 
    when: newState.changed

