#  - name: set variable
#    ansible.builtin.set_fact:
#      client_domain: "{{ inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\3') }}"
#      client_hostname: "{{ inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\2') }}"
#  - name: debug client_domain
#    ansible.builtin.debug:
#      msg: "{{ client_domain }}"

  - name: create record at cloudflare
    ansible.builtin.uri:
      url: https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records
      method: POST
      headers:
        authorization: "Bearer {{ cf_api_token }}"
      body_format: json
      body:
        type: "A"
        name: "{{ inventory_hostname }}"
        content: "{{ subnet }}.{{ vlan }}.{{ id }}"
        ttl: 1
        proxied: false
    register: create_dns_record
    ignore_errors: true
    when: (inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\3'))[0] == "pieter.fish"

  - name: create dns a record
    freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: "{{ vaulted_idm_password_nauvis }}"
      name: "{{ inventory_hostname | regex_search('(([\\w-]+)\\.)*(\\w+\\.\\w+)', '\\2') }}"
      a_ip_address: "{{ subnet }}.{{ vlan }}.{{ id }}"
      zone_name: "{{ inventory_hostname | regex_search('(([\\w-]+)\\.)*(\\w+\\.\\w+)', '\\3') | first }}."
      create_reverse: yes
    delegate_to: idm.nauvis.lan
    when: (inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\3'))[0] == "nauvis.lan"
      

