  - name: set variable
    ansible.builtin.set_fact:
      client_domain: "{{ inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\3') }}"
      client_hostname: "{{ inventory_hostname | regex_search('((\\w+)\\.)*(\\w+\\.\\w+)', '\\2') }}"
      
  - name: create record at cloudflare
    ansible.builtin.uri:
      url: https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records
      method: POST
      headers:
        authorization: "Bearer {{ cf_api_token }}"
      body_format: json
      body:
        type: "A"
        name: "{{ client_hostname }}.{{ client_domain }}"
        content: "{{ subnet }}.{{ vlan }}.{{ id }}"
        ttl: 1
        proxied: false
    register: create_dns_record
    ignore_errors: true
    when: client_domain == "pieter.fish"

  - name: create dns a record
    freeipa.ansible_freeipa.ipadnsrecord:
      ipa_server: "idm.nauvis.lan"
      ipaadmin_password: "{{ ipa.admin_password }}"
      name: "{{ client_hostname }}"
      type: "A"
      record_value: "{{ subnet }}.{{ vlan }}.{{ id }}"
      zone_name: "{{ ipa.domain }}"
    delegate_to: idm.nauvis.lan
    when: client_domain == "nauvis.lan"
      

