- name: add k8s gpg key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ release }}/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: add k8s apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ release }}/deb/ /" 
    state: present
    filename: kubernetes

- name: install k8s packages
  ansible.builtin.apt:
    name: 
      - kubeadm
      - kubectl
      - kubelet
    update_cache: yes

- name: hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold

- name: hold kubectl
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: hold kubelet
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold

- name: enable kubelet
  ansible.builtin.systemd: 
    name: kubelet
    state: started
    enabled: true
