- name: add yum repository
  ansible.builtin.yum_repository:
    name: cri-o
    description: cri-o container runtime repository for kuberentes
    file: crio.repo
    baseurl: https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ release }}/rpm/ 
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ release }}/rpm/repodata/repomd.xml.key

- name: install cri-o
  ansible.builtin.yum:
    name: 
      - cri-o
      - cri-tools
      - containernetworking-plugins
    state: present

- name: enable crio
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: true
