# playbook depends on the following galaxy collections:
# kubernetes.core
# community.general
# ansible.posix

# playbook was build with the following documentiation in mind:
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
# https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/
# https://docs.cilium.io/en/stable/installation/k8s-install-helm/

  - import_tasks: 0_system_prep.yml

  - import_tasks: 1_install_kubernetes_core_rhel.yml
    when: ansible_facts['os_family'] == 'RedHat'

  - import_tasks: 1_install_kubernetes_core_debian.yml 
    when: ansible_facts['os_family'] == 'Debian'

  - import_tasks: 2_install_container_runtime_rhel.yml
    when: ansible_facts['os_family'] == 'RedHat'

  - import_tasks: 2_install_container_runtime_debian.yml
    when: ansible_facts['os_family'] == 'Debian'

  - import_tasks: 3_bootstrap_cluster.yml

  - import_tasks: 4_installing_cilium.yml
