#TEMPLATE:
#
#GROUPNAME:
#  hosts:
#    HOSTNAME:
#      vlan: X         NOT SET BY DEFAULT, REQUIRED, RANGE OF 0-255
#      id: X           NOT SET BY DEFAULT, REQUIRED, RANGE OF 2-254
#      cpu: 4          DEFAULT VALUE, OPTIONAL
#      memory: 4096    DEFAULT VALUE, OPTIONAL
#      disk: 20        DEFAULT VALUE, OPTIONAL
#      state: 'started'  DEFAULT VALUE, OPTIONAL, OPTIONS: 'started' OR 'stopped'
#      deploy: true    DEFAULT VALUE, OPTIONAL, OPTIONS: true OR false setting this to valse disables all previously listed options
#
# IF YOU WANT TO KEEP A VM WHICH IS NOT MANAGED BY THE AUTOMATIC DEPLOY ADD ITS ID TO THE VARS:
# roles/vm-cleanup/vars/main.yml

####################
ungrouped:         #
  hosts:           #
####################
    
#    OPNsense:
#      cpu: 8
#      memory: 4096
#      disk: 32
#      deploy: false

    wireguard:
      vlan: 99
      id: 10
      zabbix: enabled

    steam:
      vlan: 102
      id: 10
      memory: 16384
      disk: 30
      state: stopped

    minecraft-david:
      vlan: 100
      id: 10
      memory: 32768
      cpu: 8
      disk: 60
      state: stopped

    zabbix-test-host:
      vlan: 100
      id: 11
      zabbix: enabled 

####################
zabbix:            #
  hosts:           #
####################

    zbx-proxy-htz01.pvisscher.nl:
      vlan: 50
      id: 11
      disk: 30

    zbx-server-htz01:
      vlan: 50
      id: 12
      disk: 100


####################
webservers:        #
  hosts:           #
####################

    bookstack:
      vlan: 100
      id: 12 
      disk: 50

    web01:
      vlan: 100
      id: 17 

####################
proxies:           #
  hosts:           #
####################

    webproxy:
      vlan: 100
      id: 16

    kube-ha-00:
      vlan: 103
      id: 13 

    kube-ha-01:
      vlan: 103
      id: 14

####################
kubernetes:        #
  hosts:           #
####################

    kube-master-00:
      vlan: 103
      id: 10

    kube-master-01:
      vlan: 103
      id: 11

    kube-master-02:
      vlan: 103
      id: 12

    kube-worker-00:
      vlan: 103
      id: 20
      disk: 50

    kube-worker-01:
      vlan: 103
      id: 21
      disk: 50

    kube-worker-02:
      vlan: 103
      id: 22
      disk: 50

    test-k8s-node-00:
      vlan: 103
      id: 200
      kubernetes: v1.29

####################
docker:            #
  hosts:           #
####################

    docker-repo.pvisscher.nl:
      vlan: 103
      id: 05
      disk: 30

####################
nick:              #
  hosts:           #
####################

    NicksFuckUp:
      vlan: 101
      id: 11
      state: stopped

    NicksWebServer:
      vlan: 101
      id: 12
      state: stopped

    nick-mail:
      vlan: 101
      id: 13
      state: stopped

    nick-mail-test:
      vlan: 101
      id: 14
      state: stopped
