- name: install freeipa 
  ansible.builtin.dnf:
    name: 
      - freeipa-server
      - freeipa-server-dns

- name: replace localhost with interface ip 
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: ^127\.0\.0\.1(?= {{ inventory_hostname }})
    replace: "{{ ansible_facts.default_ipv4.address }}"

- name: replace localhost with interface ip 
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: ^\:\:1(?= {{ inventory_hostname }})
    state: absent

- name: install freeipa-server
  ansible.builtin.command: ipa-server-install -n {{ ipa.domain }} -r {{ ipa.realm}} -a {{ ipa.admin_password }} -p {{ ipa.dm_password }} --mkhomedir --hostname={{ inventory_hostname }} --ip-address={{ ansible_facts.default_ipv4.address }} --no-ntp  --setup-dns --forwarder=1.1.1.1 -U
