name: execute AWX workflow 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'inventory.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'inventory.yml'

  workflow_dispatch:

jobs:
  execute_awx:
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4

      - name: install curl
        run: |
          sudo apt update && sudo apt install curl -y

      - name: make api call to AWX
        run: |
          curl -X POST -k https://awx.pieter.fish/api/v2/workflow_job_templates/13/launch/ -H 'Authorization: Bearer ${{ secrets.AWX_TOKEN }}'
