# This is a basic workflow to help you get started with Actions

name: running deploy script

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: arc-runner-set

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install curl
        run: |
          sudo apt update && sudo apt install curl -y

      - name: make api call to AWX
        env:
          token: ${{ secrets.AWX_TOKEN }}
        run: |
          curl -X POST -k https://awx.pieter.fish/api/v2/workflow_job_templates/13/launch/ -H 'Authorization: Bearer $env:token'
