name: execute AWX workflow 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_yaml:
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4

      - name: install yaml linting
        run: |
          sudo apt update && sudo apt install yamllint -y

      - name: make api call to AWX
        run: |
          yamllint . --exclude templates/ --exclude todo.txt --exclude secrets/
